version: "3"

networks:
    internal:

services:
    server:
        container_name: server
        image: "massivedecks/server:latest"
        environment:
            - NODE_ENV=production
            - MD_SECRET=hsdhfbsjkhdfbjhsbdfjhbs
        networks:
            - internal
        restart: unless-stopped

    client:
        container_name: client
        depends_on:
            - server
        image: "massivedecks/client:latest"
        ports:
            - "80:8080"
        networks:
            - internal
        restart: unless-stopped
